/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import CIB.Conexion;
import Op.programasOp;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julian C Vargas Q
 */
public class JInternalFrameprogramas extends javax.swing.JInternalFrame {

    programasOp p = new programasOp();
    int idfacultad;

    Conexion mysql = new Conexion();
    Connection cn = mysql.getconexion();

    String sSQL = "";
    Statement st;
    ResultSet rs;

    /**
     * Creates new form JInternalFrameprogramas
     */
    public JInternalFrameprogramas() {
        initComponents();
        cargarcbo();
    }

    public void cargarcbo() {

        this.cbofacultad.removeAllItems();

        try {

            st = cn.createStatement();
            rs = st.executeQuery("select * from facultad");
            cbofacultad.addItem("");
            while (rs.next()) {
                this.cbofacultad.addItem(rs.getString("nombfacultad"));
            }

        } catch (Exception e) {

        }

    }

    public void verprogramas() {

        DefaultTableModel dataModel;
        dataModel = p.verProgramas(idfacultad);
        // TableRowSorter<TableModel> ordenar = new TableRowSorter<TableModel>(dataModel);
        //jTableprogramas.setRowSorter(ordenar);
        jTableprogramas.setModel(dataModel);
        // jTableprogramas.setDragEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcodprog = new javax.swing.JTextField();
        txtprograma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnins_programa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableprogramas = new javax.swing.JTable();
        cbofacultad = new javax.swing.JComboBox<>();
        txtfacultad = new javax.swing.JTextField();
        btnins_facultad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtref = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodprog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodprogActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodprog, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, -1));
        getContentPane().add(txtprograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 260, -1));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel1.setText("COD. Programa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel2.setText("Referencia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        btnins_programa.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        btnins_programa.setText("Guardar ");
        btnins_programa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnins_programaActionPerformed(evt);
            }
        });
        getContentPane().add(btnins_programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 110, 51));

        jTableprogramas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        jTableprogramas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "PROGRAMA", "REF."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableprogramas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableprogramas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 590, 240));

        cbofacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbofacultad.setSelectedIndex(-1);
        cbofacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbofacultadActionPerformed(evt);
            }
        });
        getContentPane().add(cbofacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 260, -1));
        getContentPane().add(txtfacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 330, -1));

        btnins_facultad.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        btnins_facultad.setText("Añadir facultad");
        btnins_facultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnins_facultadActionPerformed(evt);
            }
        });
        getContentPane().add(btnins_facultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 160, 30));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel5.setText("Seleccionar facultad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 170, 20));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "FACULTAD"));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 540, 70));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel7.setText("Programa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));
        getContentPane().add(txtref, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 80, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PROGRAMA"));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 710, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodprogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodprogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodprogActionPerformed

    private void btnins_programaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnins_programaActionPerformed

        int posicioncbo = cbofacultad.getSelectedIndex();
        String codigo = txtcodprog.getText();
        String programa = txtprograma.getText();
        String ref = txtref.getText();

        if (posicioncbo != 0 && codigo != null && programa != null && ref != null) {
            p.registrarprograma(codigo, idfacultad, programa, ref);

            verprogramas();

        } else {
            JOptionPane.showMessageDialog(null, "No ha suministrado toda la informacion");

        }
    }//GEN-LAST:event_btnins_programaActionPerformed

    private void cbofacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbofacultadActionPerformed

        try {
            idfacultad = p.idfacultad(cbofacultad.getSelectedItem().toString());
            verprogramas();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cbofacultadActionPerformed

    private void btnins_facultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnins_facultadActionPerformed
        String facultad = txtfacultad.getText();
        int resp = JOptionPane.showConfirmDialog(null, "Desea registrar la facultad : " + facultad, "Seleccionar opcion", JOptionPane.YES_NO_OPTION);

        if (resp == 0) {
            p.registrarfacultad(facultad);
            cargarcbo();
        }

    }//GEN-LAST:event_btnins_facultadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnins_facultad;
    private javax.swing.JButton btnins_programa;
    private javax.swing.JComboBox<String> cbofacultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableprogramas;
    private javax.swing.JTextField txtcodprog;
    private javax.swing.JTextField txtfacultad;
    private javax.swing.JTextField txtprograma;
    private javax.swing.JTextField txtref;
    // End of variables declaration//GEN-END:variables
}
